
function on_receive_agent_reply(self, reply)
	local msg = reply["message"]
	print("GOT REPLY:", msg)
end

local npc_id = nil
local stream_id = -1

function init(self)
	ainpc.npc_spawn({
		["character_description"] = "A crazed scientist on the hunt for gold",
		["name"] = "Victor J. Johnson",
		["short_name"] = "Victor",
		["system_prompt"] = "",
		["voice_id"] = "test"
	},
	function(self, id)
		print("Agent spawned with id", id)
		npc_id = id

		-- Stream NPC replies
		stream_id = ainpc.npc_responses(on_receive_agent_reply,
		function(self)
			print("(finished stream)")
		end,
		function(self, err, id)
			print("Stream Failed:", err, id)		
		end)

		-- Send the first message
		ainpc.npc_chat(npc_id, {
			["game_state_info"] = "It's very hot outside",
			["sender_message"] = "Hello, how are you doing today?",
			["sender_name"] = ""
		},
		function(self)
			print("(chat success)")
		end,
		function(self, err, id)
			print("chat failed:", err, id)		
		end)
	end,
	function(self, failure, err)
		print("Agent failed to spawn:", failure, err)
	end)
end

function final(self)
	-- Kill it
	if npc_id then
		ainpc.npc_kill(npc_id, function(self)
			print("Successfully killed NPC")
			npc_id = nil
		end,
		function(self, failure, err)
			print("Agent failed to kill:", failure, err)
			-- If npc not found, we do not have a valid npc id.
			if err == 404 then
				npc_id = nil
			end
		end)
	end

	if stream_id then
		ainpc.stop_npc_responses(stream_id)
		stream_id = -1
	end
end