
function test_chat_completion()
	local t = {
		["messages"] = {
			{
				["content"] = "You are an entertaining assistant who tries to make jokes.",
				["role"] = "system"
			},
			{
				["content"] = "Hello, how are you doing today?",
				["role"] = "user"
			}
		},
		["stream"] = false
	}
	ainpc.chat_completion(t,
	function(self, result)
		print("GOT SOMETHING:")
		print(json.encode(result))
	end,
	function(self, err, id)
		print("Failed", err, id)
	end)
end

-- Chat completion can also just be a string, which will default to sending one user message.
function test_chat_completion_simple() 
	ainpc.chat_completion("Hello, what is 2 + 2?",
	function(self, result)
		print("GOT SOMETHING:")
		print(json.encode(result))
	end,
	function(self, err, id)
		print("Failed", err, id)
	end)
end

local stream_id = -1
function test_stream()
	stream_id = ainpc.npc_responses(function(self, data)
		print("GOT STREAMED:")
		print(data["count"])
		end,
	function(self)
		print("(finished stream)")
	end,
	function(self, err, id)
		print("Stream Failed:", err, id)		
	end)
end


function init(self)
	print("init")
	msg.post(".", "acquire_input_focus")
	test_chat_completion()
	-- test_chat_completion_simple()
	-- test_agent()
end

function final(self)
	if stream_id ~= -1 then
		ainpc.stop_npc_responses(stream_id)
		stream_id = -1
	end
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
